### ISSUE TITLE
일기작성, 일기내용 뷰페이지 신규 개발

### ISSUE THREAD

**Issue by geonsangyoo** [geonsangyoo/dailybear#13]
# 일기작성, 일기내용 뷰페이지 신규 개발

<br>

## As-Is (캘린더뷰에서 곰돌이 아이콘을 클릭해도 아무런 액션이 없음)

<br>

## To-Be (캘린더뷰에서 곰돌이 아이콘을 클릭하면 일기작성/일기내용 뷰페이지로 route해야함)
<img width="887" alt="image" src="https://user-images.githubusercontent.com/14138179/103494780-96a0da00-4e7b-11eb-9575-d4427cae88d9.png">

<br>

<img width="896" alt="image" src="https://user-images.githubusercontent.com/14138179/103494797-ad473100-4e7b-11eb-89bc-e8e3bef61bf8.png">

<br>

<hr>

## 🔧 To-Do 🔧 

<hr>

### 1. 일기 작성 화면 관련
- [x] 감정 곰돌이 선택 화면 개발
- [x] 일기 작성 화면 개발
- [x] 메인 캘린터뷰 화면과의 연계 개발
- [x] 일기내용을 폰 내부 DB에 저장하는 로직 개발

<hr>

### 2. 날짜별 일기 디테일 화면 관련
- [x] 곰돌이 감정 선택 화면 개발
- [x] 일기 조회 개발 (최대 height 설정 필요) >  앞뒤로 가면 일기 작성날만 보이기
- [x] 편집기능 개발 (-> 일기작성 화면으로 라우팅)
- [x] 삭제기능 개발 (DB연계 필요)
- [x] 앞뒤 날짜의 일기로 이동 개발
