### ISSUE TITLE
명언작성 뷰페이지 신규 개발

### ISSUE THREAD

**Issue by geonsangyoo** [geonsangyoo/dailybear#5]
# 명언작성 뷰페이지 신규 개발

## As-Is (캘린더뷰에서 명언 area를 클릭해도 아무런 액션이 없음)
<img width="446" alt="image" src="https://user-images.githubusercontent.com/14138179/102005984-8906a180-3d60-11eb-99ea-5a1cbee539e1.png">

## To-Be (캘린더뷰에서 명언 area를 클릭하면 명언작성 뷰페이지로 route해야함)
📌 Setting 버튼에서 이동할 수도 있지만, 새로운 이슈에서 대응 예정

<hr>

## To-Do
- [x] 명언작성 뷰페이지 개발

- [x] 랜덤기능(Random) 개발 -> 명언 데이터 외부 DB setting & 연계 기능 개발 (임시로 Firebase 활용)

- [x] 직접작성기능(Write) 개발 -> iPhone 내부 DB 연계 기능 개발

- [x] 없음(No)기능 개발 -> 캘린더뷰에 표시하지 않고, '___' (underscore) 추가

- [x] 캘린더뷰와의 연계 개발
    ✔︎ 명언작성 뷰페이지에서 설정한 값이 캘린더뷰에서 실시간 반영 되야 함
    ✔︎ 명언작성 뷰페이지의 헤더 페이지를 추가하여 back, save 버튼을 추가하여 개발해야 함
